set names utf8;
use `kpi`;

CREATE TABLE `kpi` (
  `id` INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `xmId` INT(10) NOT NULL COMMENT '项目Id',  
  `kpiId` INT(10) NOT NULL COMMENT 'kpiId',
  `kpi` DECIMAL(12,2) NOT NULL COMMENT 'kpi',
  `kpiDate` DATE NOT NULL DEFAULT 0 COMMENT 'kpi时间',
  `createTime` TIMESTAMP NOT NULL DEFAULT 0 COMMENT '创建时间',
  `updateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `xmid_kpiid_createdate_idx` (`xmId`, `kpiId`, `kpiDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;
